name = "cogcloud-data-worker"
main = "worker.js"
compatibility_date = "2025-01-01"

[vars]
AUTH_TOKEN = "cogcloud-internal-2026"
[[kv_namespaces]]
binding = "COGCLOUD_KV"
id = "d9d520972386457b8eb18f6472cb1efd"
